---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/puretego/gbpcheck.puretego.online/
    - /bin/mkdir -p $DEPLOYPATH/app $DEPLOYPATH/config
    - /bin/cp -rf app/* $DEPLOYPATH/app/
    - /bin/cp -rf config/* $DEPLOYPATH/config/
    - /bin/cp -f passenger_wsgi.py run.py requirements.txt $DEPLOYPATH/
    - /bin/touch $DEPLOYPATH/passenger_wsgi.py
